image: gitpod/workspace-dotnet

tasks:
  - init: dotnet restore

ports:
  - port: 49454
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp

github:
  prebuilds:
    master: true
    
    branches: true

    
    pullRequests: true
    
    
    addCheck: true
    
    addComment: true