name: Blueprint Release

on:
  push:
    tags:
    - 'v*'

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - name: dotnet pack
        run: dotnet pack --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}/.nupkgs -verbosity:minimal
        if: ${{ success() && github.event_name != 'pull_request' }}

      - name: dotnet nuget push
        run: dotnet nuget push ${{ github.workspace }}/.nupkgs/*.nupkg --source "github" --api-key %TOKEN%
        with:
          token: ${{ secrets.NUGET_TOKEN }}
        if: ${{ success() && github.event_name != 'pull_request' }}

      - name: Tagged Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
        if: ${{ success() && github.event_name != 'pull_request' }}
