name: Blueprint Build

# Build Variables
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  Prerelease: ci
  BuildConfiguration: Release

## CI Trigger on master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET SDK 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    - name: Setup .NET SDK 3.1.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'

    #- name: SonarCloud Preparation
    #  uses: sonarsource/sonarcloud-github-action@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration ${{ env.BuildConfiguration }} -p:Prerelease=${{ env.Prerelease }} --no-restore

    - name: dotnet test
      run: dotnet test --configuration ${{ env.BuildConfiguration }} -p:Prerelease=${{ env.Prerelease }} --no-build --no-restore --collect "Code coverage"

    - name: dotnet pack
      run: dotnet pack --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}/.nupkgs -verbosity:minimal --no-build
      if: ${{ success() && github.event_name != 'pull_request' }}

    - name: dotnet nuget push
      run: dotnet nuget push ${{ github.workspace }}/.nupkgs/*.nupkg --source "https://nuget.pkg.github.com/barclayadam/index.json" --api-key %TOKEN%
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ success() && github.event_name != 'pull_request' }}

    #- name: Analyze with SonarCloud
    #  uses: sonarsource/sonarcloud-github-action@master

    #- name: Publish SonarCloud results
    #  uses: actions/SonarCloudPublish@1
    #  with:
    #    pollingTimeoutSec: '300'
